nav-solutions/rinex

- crx2rnx/Cargo.toml
- crx2rnx/src/main.rs
- rinex-cli/Cargo.toml
- ublox-rnx/Cargo.toml
> update clap to 3.2.22

- .github/workflows/pre-release.sh
- .github/workflows/release.yml
> release.yml: cli binary packaging

- .github/workflows/release.yml
Includes @gwbres fix https://github.com/rust-build/rust-build.action/pull/60
> Update Rust build action

- rinex/Cargo.toml
Updates `geo` to 0.24.1 - no major improvements or breakage
> Update geo dependency

- README.md
- TODO.md
- doc/contribute.md
- rinex-cli/README.md
- rinex-cli/doc/analysis.md
- rinex-cli/doc/filtering.md
- rinex-cli/doc/gnss-combination.md
- rinex-cli/doc/qc.md
- rinex-cli/doc/sampling.md
- rinex/Cargo.toml
Fixes a small handful of typos in documentation.
> A bit of proofreading

- rinex/db/NAV/orbits.json
> Correct RINEX4 section

- rinex/db/NAV/orbits.json
This was omitted previously.
Fixes #79
> change iscL1C to iscL2C

- rinex/src/carrier.rs
- fix a few missing cases when identifying frequency bands in ATX records parsing
- the carrier.rs structures was vastly improved "recently", it looks like the ATX topic got left behind
-  #103
> carrier signal: improve signal identification

- .github/workflows/rust.yml
- rinex/src/ionex/record.rs
- rinex/src/lib.rs
- rinex/src/navigation/record.rs
- rinex/src/record.rs
These methods should be implemented only when the "processing" feature is enabled.
> fix feature definition

- rinex/Cargo.toml
* BeiDou carrier signals parsing in ATX
> rinex: v0.11.1

- rinex/src/navigation/ephemeris.rs
Skyplot view for GLO and GEO constellations.
Satellite positions are broadcasted in ECEF expressed in km : data is already available.
> glonass and sbas positioning

- rinex/src/lib.rs
- rinex/tests/obs.rs
Introduce new OBS RINEX iteration methods, similar to other methods recently developed.
* carrier_phase() : iterator over raw phase data
* pseudo_range(): iterator over pseudo range estimates
* ssi(): iterator over estimated signal strength
* doppler(): iterator over doppler shifts
> Introduce observation data iterators

- README.md
> add RNX2CGGTTS app

- rinex-cli/Cargo.toml
- rinex-cli/src/positioning/cggtts/post_process.rs
- sort solutions in time
- open file when -q is not active
> Improve CGGTTS formatting

- rinex/src/bibliography.rs
- rinex/src/clock/mod.rs
- rinex/src/domes.rs
- rinex/src/header.rs
- rinex/src/lib.rs
- rinex/src/tests/clock.rs
* DOMES ID# is how IGN/ITRF identifies a geodetic site
* Several RINEX files use these numbers. This PR provides abstraction and accurante description of it.
> DOMES site identifier support

- rinex-cli/src/fops.rs
- rinex/src/lib.rs
* Use the advanced production detail Batch#ID to correctly generate a batch (file serie), especially in the time binning file ops
> File batch

- rinex-cli/Cargo.toml
- rinex-cli/src/graph/record/ionosphere.rs
- rinex-cli/src/graph/record/navigation.rs
- rinex-cli/src/graph/record/observation.rs
- rinex-cli/src/graph/record/sp3_plot.rs
- rinex-cli/src/graph/skyplot.rs
- rinex-cli/src/positioning/mod.rs
- rinex-cli/src/positioning/orbit/mod.rs
- rinex-cli/src/positioning/orbit/nav.rs
- rinex-cli/src/positioning/orbit/sp3.rs
- rinex/src/constants.rs
- rinex/src/lib.rs
- rinex/src/navigation/ephemeris.rs
- rinex/src/tests/nav.rs
Also _temporarily_ switch to my fork of gnss-rtk until the PR is merged.
Companion PR to https://github.com/rtk-rs/gnss-rtk/pull/18 .
> Switch from MetaFile to embedded Almanac ephem

- rinex-cli/src/graph/record/ionosphere.rs
- rinex-cli/src/graph/record/navigation.rs
- rinex-cli/src/graph/record/observation.rs
- rinex-cli/src/graph/record/sp3_plot.rs
- rinex-cli/src/graph/skyplot.rs
- rinex-cli/src/positioning/mod.rs
- rinex-cli/src/positioning/orbit/mod.rs
- rinex-cli/src/positioning/orbit/nav.rs
- rinex/Cargo.toml
- rinex/src/lib.rs
- rinex/src/navigation/ephemeris.rs
- rinex/src/tests/nav.rs
Backport to latest stable state, leave a few things commented out
> kepler solver

- binex/Cargo.toml
> BINEX v0.4

- rinex-cli/src/positioning/cggtts/mod.rs
see: https://github.com/georust/rinex/issues/285
> Fix track duration, in CGGTTS tracking #285

- rinex/src/hatanaka/compressor.rs
- rinex/src/observation/mod.rs
- rinex/src/record/formatting.rs
- rinex/src/tests/compression.rs
Good progress in the quality of the CRINEX we synthesize. Still, this is not OK yet (work in progress)
> RINEX Compression

- rinex/src/binex/rnx2bin/mod.rs
- rinex/src/binex/rnx2bin/nav.rs
* introduce option to skip header serialization
* introduce option for a custom header message
> RINEX2BIN: special options

- src/hatanaka/compressor.rs
- src/tests/compression.rs
* RNX2CRX v3 starting to give good results
> Hatanaka compression

- src/header/mod.rs
- src/header/parsing.rs
- src/header/processing.rs
- src/qc/merge/header.rs
- src/tests/toolkit/mod.rs
* Qc: remove glonass specs when glonass is being dropped
* remove gps_utc_delta: replaced by TimeOffset & polynomials
> Small improvements

- src/processing/timeshift.rs
* GnssAbsoluteTime upgrade
* Header: round timestamps to 1e-6
> Update to latest libs

- Cargo.toml
- src/epoch.rs
- src/hatanaka/textdiff.rs
- src/header/parsing.rs
- src/navigation/ephemeris/mod.rs
- src/navigation/rinex/feature.rs
- src/navigation/time/parsing.rs
- src/reader.rs
- src/record/parsing.rs
- src/tests/crinex/decompression/mod.rs
- src/tests/kepler.rs
- src/tests/toolkit/observation.rs
* This may rise when falsely invoking from_file on a Gzip header
* or invoking from_gzip_file on a readable header
> Remove unwrap (catching I/O error nicely)

- Cargo.toml
- make Ephemeris.format public
> release v0.21.1: slight api update
