nav-solutions/rinex

crx2rnx/Cargo.toml, rinex-cli/Cargo.toml, ublox-rnx/Cargo.toml
I noticed that a rather old version of clap is being used currently, in crx2rnx, ublox-rnx and rinex-cli.
Version 3 has [many breaking changes](https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#300---2021-12-31), so I thought of bumping to 2.34 for now.
=> Update clap to 2.34

sinex/Cargo.toml
Moving from 0.3.3 to the local version like the other tools
=> Let `sinex` use the current version of `rinex`

.github/workflows/Audit.yml
The time/chrono RUSTSEC advisories can be effectively ignored, as they do not pose a real threat.
=> Ignore this cargo audit warning - it is not a problem

rinex-cli/src/main.rs
Letting `clap` display the help information when no parameter is given to `rinex-cli`
Fixes #15
=> Show help if no parameters

rinex/Cargo.toml
Required to use the `vec_retain_mut` feature.
Fixes #17
=> Set minimum Rust version to 1.61

.github/workflows/Audit.yml
The audit no longer gives a failed result upon a CVE, and the check was wrong anyway (was RUSTSEC-2020-007, should have been RUSTSEC-2020-0071)
=> Remove exception from `cargo audit`

crx2rnx/Cargo.toml, rinex-cli/Cargo.toml, rinex/Cargo.toml, rnx2crx/Cargo.toml, sinex/Cargo.toml, ublox-rnx/Cargo.toml
Since we're requiring Rust 1.61 anyway, we might as well use the 2021 edition introduced in 1.56.
=> Update Rust edition to 2021

rinex-cli/src/cli.rs
This reintroduces the option of showing the help if no argument is provided.
=> Reapply showing help if no argument

.github/workflows/release.yml, TODO.md
Adding this because we might easier get feedback from GNSS professionals who are not Rust proficient if they can download a binary of 'rinex-cli'.
=> Add task: automatic building of binaries

rinex/Cargo.toml, rinex/src/antex/frequency.rs, rinex/src/antex/pcv.rs, rinex/src/channel.rs, rinex/src/epoch/flag.rs, rinex/src/hardware.rs, rinex/src/ionex/grid.rs, rinex/src/ionex/system.rs, rinex/src/navigation/health.rs, rinex/src/navigation/ionmessage.rs
* answers https://github.com/gwbres/rinex/issues/65 enhancement requests
=> increase code coverage

.gitignore
These turn up all the time on macOS, so we should ignore them.
=> ignore macOS .DS_Store files

rinex/Cargo.toml
Since our required features in HiFiTime are now in 3.8, we can switch to it instead of using the latest state of the repo.
=> Use 3.8 instead of latest commit

rinex-cli/Cargo.toml
`atty` 0.2.14 is vulnerable to Potential unaligned read. A newer version of `pretty_env_logger` replaces this with `is-terminal`.
=> update pretty_env_logger to reduce dependency on atty

.github/workflows/Audit.yml, .github/workflows/rust.yml
Should get rid of Node deprecation warnings.
=> update checkout action to v3

README.md, rinex-cli/Cargo.toml, rinex/Cargo.toml, rinex/README.md
The use of "indexmap"/"hashbrown" has increased the minimumt rustc required. 
I think it is tied to IONEX/maps operations.
The ionex infra will get finalized and aligned to latest work, so that probably will not last for long.
=> update minimum rustc requirement

rinex/src/carrier.rs
Additional changes related to #103 . Specifically changing the BeiDou parsing to return BeiDou carrier codes and to add a parsing for an additional IRNSS code.
=> Update parsing of BDS and IRNSS carrier codes

rinex/build.rs, rinex/db/NAV/orbits.json, rinex/src/algorithm/target.rs, rinex/src/navigation/ephemeris.rs, rinex/src/navigation/orbits.rs, rinex/src/navigation/record.rs, rinex/src/version.rs, rinex/tests/nav.rs
Preliminary work to support CNAV, CNAV-2 and other modern Ephemeris frames.
----
Answers 
preliminary work to provide an answer to 
- #78
- and #80
To fully support NAV-V4, we need a slightly more complex Navigation Frame database, 
because the frames content now depends on `NavMsgType` also.
Therefore, this field needs to be introduced in the database, and taken care of.
This branch only introduces the foundation and we still only truly support `NavMsgType::LNAV` only.  
Modern frames will be introduced in following contributions.
- Modified (and simplified) the JSON description to describe the `NavMsgType`. 
This modification also impacts the Rinex filter designer, because filtering on Nav Orbit Fields is one possible type of filter.
The `build.rs` script is slightly improved:
- Don't …
=> NAV V4: RINEX V4 navigation support

.github/workflows/release.yml
Updates the (currently) unused build action as the first part of an attempt to revitalize them
=> Update release build action

rinex/Cargo.toml, rinex/src/tests/compression.rs, rinex/src/tests/production.rs, rinex/src/tests/toolkit.rs
since we split the QC into a separate library
With this simple random name generator, we make sure each tasklet creates a unique file.  
We also made sure, in a previous contribution, that all temporary generated files get removed at the end of the test execution.
=> only rinex-qc and cli need SP3 dependency

README.md, crx2rnx/README.md, rinex-cli/README.md, rinex-cli/doc/analysis.md, rinex-cli/doc/cycle-slip.md, rinex-cli/doc/gnss-combination.md, rinex-cli/doc/positioning.md, rinex-cli/doc/processing.md, rinex-cli/doc/record.md, rnx2crx/README.md, sinex/README.md, ublox-rnx/src/main.rs
Simply updates a lot of `gwbres/rinex` links to `georust/rinex`.
=> Update old links to GeoRust

crx2rnx/Cargo.toml, rinex-cli/Cargo.toml, rinex-qc/Cargo.toml, rinex/Cargo.toml, rinex/src/epoch/mod.rs, rinex/src/lib.rs, rinex/src/tests/filename.rs, rnx2crx/Cargo.toml, sp3/Cargo.toml, ublox-rnx/Cargo.toml
* fixes standardized filename generator
=> bump hifitime to v3.9.0

rinex-cli/src/cli/graph.rs, rinex-cli/src/cli/identify.rs, rinex-cli/src/cli/mod.rs
Fixes several runtime crashes that I ran into while trying to use rinex-cli.
=> Fix rinex-cli commands

rinex-cli/src/cli/mod.rs
The rx-geo parameter expects lat/lon in degrees, but the geodetic2ecef function wants them in radians. This leads to positions being wildly incorrect. This commit switches to calling the GroundPosition::from_geodetic function instead, which is happy to directly recieve the lat/lon/alt tuple as-is without conversion.
=> Fix rinex-cli interpretation of rx-geo

rinex/src/header.rs, rinex/src/observation/record.rs, rinex/src/tests/production.rs
=> OBS V3 formatting

rinex-cli/src/teqc/ascii_plot.rs, sinex/src/bias/mod.rs
Duration is now simply an alias of TimeDelta kept for backwards compatibility.
=> switch from chrono::Duration to chrono::TimeDelta

rinex-cli/src/cli/fops/filegen.rs, rinex-cli/src/positioning/ppp/post_process.rs
The geo_point::Point is initalized with an (X, Y) coordinate, which it interprets as (longitude, latitude). We currently intialize the point in the wrong order which results in incorrect GPX output.
=> Swap latitude and longitude in GPX output

rinex-cli/src/graph/record/observation.rs, rinex/src/lib.rs
- Bad scaling was applied at entry point of the API, SV coordinates are now expressed in km all the time
- Introduce possibitliy to determine such information from radio broadcasted data only
=> Fix SV_Elev plotting in coherent OBS/NAV/SP3 rinex scenarios

ublox-rnx/Cargo.toml
So that relevant structs are visible and ublox-rnx compiles
=> fix: add feature clock to ublox-rnx

rinex/src/header.rs
=> Fix empty constellation case (old RINEX format)

rinex/src/doris/mod.rs, rinex/src/doris/record.rs, rinex/src/doris/station.rs, rinex/src/epoch.rs, rinex/src/header.rs, rinex/src/observable.rs, rinex/src/tests/toolkit/mod.rs, rinex/src/tests/toolkit/observation.rs
- Removes one memory allocation in the parsing process (slight improvement)
- Run clippy
=> Remove malloc in CRINEX header parsing

rinex-cli/src/cli/graph.rs, rinex-cli/src/cli/positioning.rs, rinex-cli/src/graph/mod.rs, rinex-cli/src/main.rs
- Minor fixes in some plot titles
- Provide more direct examples with `--help`
=> Cli (Help and Improvements)

rinex-cli/Cargo.toml, rinex-cli/src/graph/mod.rs, rinex-cli/src/positioning/orbit/mod.rs, rinex-cli/src/positioning/orbit/sp3.rs, rinex-qc/Cargo.toml, rinex/Cargo.toml, rinex/src/navigation/ephemeris.rs, sinex/Cargo.toml, sp3/Cargo.toml, ublox-rnx/Cargo.toml
Following our conversation from https://github.com/orgs/nyx-space/discussions/310, I'm proposing switching to ANISE for the computation of the Earth centered Earth fixed (ECEF) position and velocity. Note that, in my experience with deep space navigation, we typically use only the "IAU Earth" or the augmented "ITRF93" frames: both are Earth centered Earth fixed frames, but they are more rigorously defined. The IAU Earth frame uses the precession, long term and short term nutation parameters defined [here](https://github.com/nyx-space/anise/blob/master/data/pck00008.tpc#L821). The ITRF93 frame is a frame reconstructed from the actual observations of the stars: it is more precise than the IAU Earth frame, but that precision is rarely needed for Earth orbiting spacecraft.
One of the main …
=> Switch to ANISE for ECEF (IAU Earth) computation

rinex/src/lib.rs, rinex/src/navigation/ephemeris.rs
* Some code portions are feature dependent, and CI/CD did not pick this up
=> Fix nav/doris feature definition

binex/README.md, binex/src/decoder.rs, binex/src/lib.rs, binex/src/message/checksum.rs, binex/src/message/meta.rs, binex/src/message/mid.rs, binex/src/message/mod.rs, binex/src/message/record/ephemeris/galileo.rs, binex/src/message/record/ephemeris/glonass.rs, binex/src/message/record/ephemeris/gps/eph.rs, binex/src/message/record/ephemeris/gps/raw.rs, binex/src/message/record/ephemeris/mod.rs, binex/src/message/record/ephemeris/sbas.rs, binex/src/message/record/monument/mod.rs, binex/src/message/record/solutions/frame/ecef.rs, binex/src/message/record/solutions/frame/geo.rs, binex/src/message/record/solutions/frame/mod.rs, binex/src/message/record/solutions/frame/temporal.rs, binex/src/message/record/solutions/mod.rs, binex/src/stream.rs, binex/src/utils.rs
+ fix bug on MLEN for large messages
+ verify little endian encoding & decoding
+ unlock support
+ update docs
=> BINEX: little endian streams

rinex-cli/src/positioning/cggtts/mod.rs
I tried to use rinex-cli to create CGGTTS from RINEX, but it failed(not enough candidates match post-fit criteria). After some debugging, I found that the issue occurs when the observation interval is 1 second.
When the observation interval is 1 second, the line if t >= next_release is called twice within the same track, causing the track to be reset twice. (Note: t == next_release, but sched.next_track_start(*t) does not update next_release.)
I attempted to fix the bug, and the code now works. However, I am not sure if the measurements in the track are correct. Please review the code.
Thank you.
=> Fix CGGTTS error when the observation interval is 1 second

rinex-cli/src/positioning/cggtts/mod.rs
To test the tracker, I used `./tutorials/CGGTTS/mojndnk` focused on `E05+E09`
Results with current version:
Results with the proposal :
@vicalloy,
note that the CGGTTS scheduler is tested in cggtts/track/scheduler, for example the initial point in any day is tested thoroughly
=> Fix track midpoint determination, in CGGTTS tracking

rinex-cli/src/positioning/cggtts/mod.rs
If `tracker.fit fails`, `tracker.reset()` will not be called, and the samples will be kept for the next period.
This commit resets the tracker after tacker release.
=> Fix CGGTTS, reset the tracker after it is released.

rinex-cli/src/cli/mod.rs, rinex-cli/src/main.rs, rinex-qc/README.md, rinex-qc/src/context.rs
Fix offline/online deployment options
- a new --jpl-bpc option is introduced in RINEX-Cli
Which always requires internet access and IS THE ONLY OPTION
to keep the JPL model up to date.
- the local storage is preserved and allows fast deployments
(after a first successful deployment)
- for example, in the past few days the JPL servers have been down.
When deploying without --jpl-bpc:
- the session will rely on the previous JPL model if it was already downloaded.
If this model is too old and servers remain down, you should delete it !
- the session will rely on low precision (offline) model until a JPL model
has been obtained
When deploying with --jpl-bpc:
- the session will crash because correct network access is expected
=> Jpl gh 286

src/navigation/mask.rs
* temporal masking, when applied to Navigation Ephemerides is dangerous. 
We might propose it, either differently (at a higher level) or through special options. 
SV / Constellation is perfectly safe and sane, and is already more than enough to for a preprocessing pipeline
=> Remove Temporal Masking
